 stages:
   - apply_config
   - test

 ansible_job:
     stage: apply_config
     tags:
        - tag1
     script:
        - ansible-playbook -i ansible/hosts QoS/shaping.yaml

 generator_traffic_job:
     stage: test
     tags:
        - tag1
     script:
        - ITGSend tests/sh_flow
        - ansible-playbook -i ansible/hosts tests/test.yaml
        - ITGDec result_tests/res1.txt > result_tests/result_generator.txt
        - ITGDec result_tests/res1.txt 
     artifacts:
       paths:
        - result_tests/result_generator.txt
