 stages:
   - apply_config
   - test
   - info_gather

 ansible_job:
     stage: apply_config
     tags:
        - tag1
     script:
        - ansible-playbook -i ansible/hosts QoS/shaping/shaping.yaml

 generator_traffic_job:
     stage: test
     tags:
        - tag1
     script:
        - ITGSend QoS/tests/sh_flow
        - ansible-playbook -i ansible/hosts QoS/tests/copy.yaml
        - ITGDec res.txt > result_generator.txt
        - ITGDec res.txt 
     artifacts:
       paths:
        - configs

 info_gather_job:
     stage: info_gather
     tags:
        - tag1
     script:
        - mkdir configs
        - ansible-playbook -i ansible/hosts QoS/tests/info_gather.yaml
     artifacts:
       paths:
        - configs
