 stages:
   - apply_ansible
   - test1

 ifconfig_job:
     stage: apply_ansible
     tags:
        - tag1
     script:
        - ansible-playbook -i ansible/hosts QoS/shaping.yaml

 ping_test_job:
     stage: test1
     tags:
        - tag1
     script:
        - ITGSend tests/sh_flow



